package wrappergen

import (
	"bytes"
	"fmt"
	"go/format"
	"regexp"
	"sort"
	"strings"
	"unicode"

	"github.com/SPShota/terraform-provider-tensorflow/internal/manifest"
)

type Options struct {
	PackageName  string
	FunctionName string
}

type Wrapper struct {
	TypeNameSuffix string
	Function       string
	DocURL         string
}

func Generate(m manifest.Manifest, opts Options) ([]byte, error) {
	if err := m.Validate(); err != nil {
		return nil, err
	}

	packageName := opts.PackageName
	if packageName == "" {
		packageName = "provider"
	}

	functionName := opts.FunctionName
	if functionName == "" {
		functionName = "GeneratedDataSources"
	}

	wrappers, err := Wrappers(m)
	if err != nil {
		return nil, err
	}

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by tftf-wrappergen. DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", packageName)
	fmt.Fprintf(&buf, "import \"github.com/hashicorp/terraform-plugin-framework/datasource\"\n\n")
	fmt.Fprintf(&buf, "func %s() []func() datasource.DataSource {\n", functionName)
	fmt.Fprintf(&buf, "\treturn []func() datasource.DataSource{\n")
	for _, wrapper := range wrappers {
		fmt.Fprintf(&buf, "\t\tfunc() datasource.DataSource {\n")
		fmt.Fprintf(&buf, "\t\t\treturn NewWrapperDataSource(WrapperDataSourceSpec{\n")
		fmt.Fprintf(&buf, "\t\t\t\tTypeNameSuffix: %q,\n", wrapper.TypeNameSuffix)
		fmt.Fprintf(&buf, "\t\t\t\tFunction: %q,\n", wrapper.Function)
		if wrapper.DocURL != "" {
			fmt.Fprintf(&buf, "\t\t\t\tDocURL: %q,\n", wrapper.DocURL)
		}
		fmt.Fprintf(&buf, "\t\t\t})\n")
		fmt.Fprintf(&buf, "\t\t},\n")
	}
	fmt.Fprintf(&buf, "\t}\n")
	fmt.Fprintf(&buf, "}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}

	return formatted, nil
}

func Wrappers(m manifest.Manifest) ([]Wrapper, error) {
	wrappers := make([]Wrapper, 0, len(m.Symbols))
	seen := map[string]string{}

	for _, symbol := range m.Symbols {
		if !isWrappable(symbol) {
			continue
		}

		suffix, err := TypeNameSuffix(m.Root, symbol.Path)
		if err != nil {
			return nil, err
		}
		if previous, ok := seen[suffix]; ok {
			return nil, fmt.Errorf("duplicate wrapper suffix %q for %q and %q", suffix, previous, symbol.Path)
		}
		seen[suffix] = symbol.Path

		wrappers = append(wrappers, Wrapper{
			TypeNameSuffix: suffix,
			Function:       symbol.Path,
			DocURL:         symbol.DocURL,
		})
	}

	sort.Slice(wrappers, func(i, j int) bool {
		return wrappers[i].TypeNameSuffix < wrappers[j].TypeNameSuffix
	})

	return wrappers, nil
}

func TypeNameSuffix(root, path string) (string, error) {
	if root == "" {
		return "", fmt.Errorf("root must not be empty")
	}
	if path == root {
		return "", fmt.Errorf("root symbol %q is not wrappable", path)
	}

	prefix := root + "."
	if !strings.HasPrefix(path, prefix) {
		return "", fmt.Errorf("symbol path %q does not start with %q", path, prefix)
	}

	parts := strings.Split(strings.TrimPrefix(path, prefix), ".")
	snakeParts := make([]string, 0, len(parts))
	for _, part := range parts {
		snake, err := snakeIdentifier(part)
		if err != nil {
			return "", fmt.Errorf("symbol path %q: %w", path, err)
		}
		snakeParts = append(snakeParts, snake)
	}

	return strings.Join(snakeParts, "_"), nil
}

func isWrappable(symbol manifest.Symbol) bool {
	switch symbol.Kind {
	case "function", "class", "callable":
		return symbol.Path != ""
	default:
		return false
	}
}

var invalidIdentifierCharacters = regexp.MustCompile(`[^a-z0-9_]+`)

func snakeIdentifier(value string) (string, error) {
	if value == "" {
		return "", fmt.Errorf("identifier part must not be empty")
	}

	var out strings.Builder
	for i, r := range value {
		if unicode.IsUpper(r) {
			if i > 0 {
				out.WriteByte('_')
			}
			out.WriteRune(unicode.ToLower(r))
			continue
		}
		out.WriteRune(unicode.ToLower(r))
	}

	snake := invalidIdentifierCharacters.ReplaceAllString(out.String(), "_")
	snake = strings.Trim(snake, "_")
	for strings.Contains(snake, "__") {
		snake = strings.ReplaceAll(snake, "__", "_")
	}

	if snake == "" {
		return "", fmt.Errorf("identifier part %q cannot be converted to a Terraform type suffix", value)
	}
	if snake[0] >= '0' && snake[0] <= '9' {
		snake = "n_" + snake
	}

	return snake, nil
}
