// Code generated by tftf-wrappergen. DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/datasource"

func GeneratedDataSources() []func() datasource.DataSource {
	return []func() datasource.DataSource{
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "boolean_mask",
				Function:       "tf.boolean_mask",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/boolean_mask",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "cast",
				Function:       "tf.cast",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/cast",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "concat",
				Function:       "tf.concat",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/concat",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "constant",
				Function:       "tf.constant",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/constant",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "convert_to_tensor",
				Function:       "tf.convert_to_tensor",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/convert_to_tensor",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "expand_dims",
				Function:       "tf.expand_dims",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/expand_dims",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "fill",
				Function:       "tf.fill",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/fill",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "gather",
				Function:       "tf.gather",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/gather",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "gather_nd",
				Function:       "tf.gather_nd",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/gather_nd",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "linspace",
				Function:       "tf.linspace",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/linspace",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "math_abs",
				Function:       "tf.math.abs",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/math/abs",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "math_add",
				Function:       "tf.math.add",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/math/add",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "math_divide",
				Function:       "tf.math.divide",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/math/divide",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "math_equal",
				Function:       "tf.math.equal",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/math/equal",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "math_maximum",
				Function:       "tf.math.maximum",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/math/maximum",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "math_minimum",
				Function:       "tf.math.minimum",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/math/minimum",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "math_multiply",
				Function:       "tf.math.multiply",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/math/multiply",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "math_reduce_max",
				Function:       "tf.math.reduce_max",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/math/reduce_max",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "math_reduce_mean",
				Function:       "tf.math.reduce_mean",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/math/reduce_mean",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "math_reduce_min",
				Function:       "tf.math.reduce_min",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/math/reduce_min",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "math_reduce_sum",
				Function:       "tf.math.reduce_sum",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/math/reduce_sum",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "math_sqrt",
				Function:       "tf.math.sqrt",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/math/sqrt",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "math_square",
				Function:       "tf.math.square",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/math/square",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "math_subtract",
				Function:       "tf.math.subtract",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/math/subtract",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "ones",
				Function:       "tf.ones",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/ones",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "ones_like",
				Function:       "tf.ones_like",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/ones_like",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "range",
				Function:       "tf.range",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/range",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "rank",
				Function:       "tf.rank",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/rank",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "reshape",
				Function:       "tf.reshape",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/reshape",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "shape",
				Function:       "tf.shape",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/shape",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "size",
				Function:       "tf.size",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/size",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "split",
				Function:       "tf.split",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/split",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "squeeze",
				Function:       "tf.squeeze",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/squeeze",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "stack",
				Function:       "tf.stack",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/stack",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "transpose",
				Function:       "tf.transpose",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/transpose",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "unstack",
				Function:       "tf.unstack",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/unstack",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "where",
				Function:       "tf.where",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/where",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "zeros",
				Function:       "tf.zeros",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/zeros",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "zeros_like",
				Function:       "tf.zeros_like",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/zeros_like",
			})
		},
	}
}
