// Code generated by tftf-wrappergen. DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/datasource"

func GeneratedDataSources() []func() datasource.DataSource {
	return []func() datasource.DataSource{
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "audio_decode_wav",
				Function:       "tf.audio.decode_wav",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/audio/decode_wav",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "audio_encode_wav",
				Function:       "tf.audio.encode_wav",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/audio/encode_wav",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "boolean_mask",
				Function:       "tf.boolean_mask",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/boolean_mask",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "cast",
				Function:       "tf.cast",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/cast",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "concat",
				Function:       "tf.concat",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/concat",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "constant",
				Function:       "tf.constant",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/constant",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "convert_to_tensor",
				Function:       "tf.convert_to_tensor",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/convert_to_tensor",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "data_dataset_from_generator",
				Function:       "tf.data.Dataset.from_generator",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/data/Dataset#from_generator",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "data_dataset_from_tensor_slices",
				Function:       "tf.data.Dataset.from_tensor_slices",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/data/Dataset#from_tensor_slices",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "data_dataset_from_tensors",
				Function:       "tf.data.Dataset.from_tensors",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/data/Dataset#from_tensors",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "data_dataset_list_files",
				Function:       "tf.data.Dataset.list_files",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/data/Dataset#list_files",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "data_dataset_range",
				Function:       "tf.data.Dataset.range",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/data/Dataset#range",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "data_dataset_zip",
				Function:       "tf.data.Dataset.zip",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/data/Dataset#zip",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "data_tf_record_dataset",
				Function:       "tf.data.TFRecordDataset",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/data/TFRecordDataset",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "expand_dims",
				Function:       "tf.expand_dims",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/expand_dims",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "fill",
				Function:       "tf.fill",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/fill",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "gather",
				Function:       "tf.gather",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/gather",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "gather_nd",
				Function:       "tf.gather_nd",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/gather_nd",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "gradient_tape",
				Function:       "tf.GradientTape",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/GradientTape",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "image_adjust_brightness",
				Function:       "tf.image.adjust_brightness",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/image/adjust_brightness",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "image_convert_image_dtype",
				Function:       "tf.image.convert_image_dtype",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/image/convert_image_dtype",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "image_crop_to_bounding_box",
				Function:       "tf.image.crop_to_bounding_box",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/image/crop_to_bounding_box",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "image_decode_image",
				Function:       "tf.image.decode_image",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/image/decode_image",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "image_flip_left_right",
				Function:       "tf.image.flip_left_right",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/image/flip_left_right",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "image_random_flip_left_right",
				Function:       "tf.image.random_flip_left_right",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/image/random_flip_left_right",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "image_resize",
				Function:       "tf.image.resize",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/image/resize",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "io_decode_csv",
				Function:       "tf.io.decode_csv",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/io/decode_csv",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "io_decode_json_example",
				Function:       "tf.io.decode_json_example",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/io/decode_json_example",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "io_decode_raw",
				Function:       "tf.io.decode_raw",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/io/decode_raw",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "io_encode_base64",
				Function:       "tf.io.encode_base64",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/io/encode_base64",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "io_parse_example",
				Function:       "tf.io.parse_example",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/io/parse_example",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "io_read_file",
				Function:       "tf.io.read_file",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/io/read_file",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "io_write_file",
				Function:       "tf.io.write_file",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/io/write_file",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "keras_input",
				Function:       "tf.keras.Input",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/keras/Input",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "keras_layers_activation",
				Function:       "tf.keras.layers.Activation",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/keras/layers/Activation",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "keras_layers_batch_normalization",
				Function:       "tf.keras.layers.BatchNormalization",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/keras/layers/BatchNormalization",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "keras_layers_conv2_d",
				Function:       "tf.keras.layers.Conv2D",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/keras/layers/Conv2D",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "keras_layers_dense",
				Function:       "tf.keras.layers.Dense",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dense",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "keras_layers_dropout",
				Function:       "tf.keras.layers.Dropout",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dropout",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "keras_layers_embedding",
				Function:       "tf.keras.layers.Embedding",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/keras/layers/Embedding",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "keras_layers_flatten",
				Function:       "tf.keras.layers.Flatten",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/keras/layers/Flatten",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "keras_layers_global_average_pooling2_d",
				Function:       "tf.keras.layers.GlobalAveragePooling2D",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/keras/layers/GlobalAveragePooling2D",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "keras_layers_input_layer",
				Function:       "tf.keras.layers.InputLayer",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/keras/layers/InputLayer",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "keras_layers_lstm",
				Function:       "tf.keras.layers.LSTM",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/keras/layers/LSTM",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "keras_layers_max_pooling2_d",
				Function:       "tf.keras.layers.MaxPooling2D",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/keras/layers/MaxPooling2D",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "keras_losses_binary_crossentropy",
				Function:       "tf.keras.losses.BinaryCrossentropy",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/keras/losses/BinaryCrossentropy",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "keras_losses_categorical_crossentropy",
				Function:       "tf.keras.losses.CategoricalCrossentropy",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/keras/losses/CategoricalCrossentropy",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "keras_losses_mean_squared_error",
				Function:       "tf.keras.losses.MeanSquaredError",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/keras/losses/MeanSquaredError",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "keras_losses_sparse_categorical_crossentropy",
				Function:       "tf.keras.losses.SparseCategoricalCrossentropy",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/keras/losses/SparseCategoricalCrossentropy",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "keras_metrics_accuracy",
				Function:       "tf.keras.metrics.Accuracy",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/keras/metrics/Accuracy",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "keras_metrics_auc",
				Function:       "tf.keras.metrics.AUC",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/keras/metrics/AUC",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "keras_metrics_binary_accuracy",
				Function:       "tf.keras.metrics.BinaryAccuracy",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/keras/metrics/BinaryAccuracy",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "keras_metrics_categorical_accuracy",
				Function:       "tf.keras.metrics.CategoricalAccuracy",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/keras/metrics/CategoricalAccuracy",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "keras_metrics_mean",
				Function:       "tf.keras.metrics.Mean",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/keras/metrics/Mean",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "keras_metrics_sparse_categorical_accuracy",
				Function:       "tf.keras.metrics.SparseCategoricalAccuracy",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/keras/metrics/SparseCategoricalAccuracy",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "keras_model",
				Function:       "tf.keras.Model",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/keras/Model",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "keras_optimizers_adam",
				Function:       "tf.keras.optimizers.Adam",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "keras_optimizers_rmsprop",
				Function:       "tf.keras.optimizers.RMSprop",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/RMSprop",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "keras_optimizers_sgd",
				Function:       "tf.keras.optimizers.SGD",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/SGD",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "keras_sequential",
				Function:       "tf.keras.Sequential",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/keras/Sequential",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "linspace",
				Function:       "tf.linspace",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/linspace",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "math_abs",
				Function:       "tf.math.abs",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/math/abs",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "math_add",
				Function:       "tf.math.add",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/math/add",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "math_divide",
				Function:       "tf.math.divide",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/math/divide",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "math_equal",
				Function:       "tf.math.equal",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/math/equal",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "math_maximum",
				Function:       "tf.math.maximum",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/math/maximum",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "math_minimum",
				Function:       "tf.math.minimum",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/math/minimum",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "math_multiply",
				Function:       "tf.math.multiply",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/math/multiply",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "math_reduce_max",
				Function:       "tf.math.reduce_max",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/math/reduce_max",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "math_reduce_mean",
				Function:       "tf.math.reduce_mean",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/math/reduce_mean",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "math_reduce_min",
				Function:       "tf.math.reduce_min",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/math/reduce_min",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "math_reduce_sum",
				Function:       "tf.math.reduce_sum",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/math/reduce_sum",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "math_sqrt",
				Function:       "tf.math.sqrt",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/math/sqrt",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "math_square",
				Function:       "tf.math.square",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/math/square",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "math_subtract",
				Function:       "tf.math.subtract",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/math/subtract",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "module",
				Function:       "tf.Module",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/Module",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "ones",
				Function:       "tf.ones",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/ones",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "ones_like",
				Function:       "tf.ones_like",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/ones_like",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "range",
				Function:       "tf.range",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/range",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "rank",
				Function:       "tf.rank",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/rank",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "ragged_boolean_mask",
				Function:       "tf.ragged.boolean_mask",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/ragged/boolean_mask",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "ragged_constant",
				Function:       "tf.ragged.constant",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/ragged/constant",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "ragged_map_flat_values",
				Function:       "tf.ragged.map_flat_values",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/ragged/map_flat_values",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "random_categorical",
				Function:       "tf.random.categorical",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/random/categorical",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "random_normal",
				Function:       "tf.random.normal",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/random/normal",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "random_set_seed",
				Function:       "tf.random.set_seed",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/random/set_seed",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "random_shuffle",
				Function:       "tf.random.shuffle",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/random/shuffle",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "random_uniform",
				Function:       "tf.random.uniform",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/random/uniform",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "reshape",
				Function:       "tf.reshape",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/reshape",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "shape",
				Function:       "tf.shape",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/shape",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "size",
				Function:       "tf.size",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/size",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "split",
				Function:       "tf.split",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/split",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "sparse_add",
				Function:       "tf.sparse.add",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/sparse/add",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "sparse_concat",
				Function:       "tf.sparse.concat",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/sparse/concat",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "sparse_reorder",
				Function:       "tf.sparse.reorder",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/sparse/reorder",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "sparse_reshape",
				Function:       "tf.sparse.reshape",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/sparse/reshape",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "sparse_reset_shape",
				Function:       "tf.sparse.reset_shape",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/sparse/reset_shape",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "sparse_to_dense",
				Function:       "tf.sparse.to_dense",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/sparse/to_dense",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "squeeze",
				Function:       "tf.squeeze",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/squeeze",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "stack",
				Function:       "tf.stack",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/stack",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "strings_join",
				Function:       "tf.strings.join",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/strings/join",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "strings_length",
				Function:       "tf.strings.length",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/strings/length",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "strings_lower",
				Function:       "tf.strings.lower",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/strings/lower",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "strings_regex_replace",
				Function:       "tf.strings.regex_replace",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/strings/regex_replace",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "strings_split",
				Function:       "tf.strings.split",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/strings/split",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "strings_strip",
				Function:       "tf.strings.strip",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/strings/strip",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "strings_to_number",
				Function:       "tf.strings.to_number",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/strings/to_number",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "strings_upper",
				Function:       "tf.strings.upper",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/strings/upper",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "transpose",
				Function:       "tf.transpose",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/transpose",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "unstack",
				Function:       "tf.unstack",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/unstack",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "variable",
				Function:       "tf.Variable",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/Variable",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "where",
				Function:       "tf.where",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/where",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "zeros",
				Function:       "tf.zeros",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/zeros",
			})
		},
		func() datasource.DataSource {
			return NewWrapperDataSource(WrapperDataSourceSpec{
				TypeNameSuffix: "zeros_like",
				Function:       "tf.zeros_like",
				DocURL:         "https://www.tensorflow.org/api_docs/python/tf/zeros_like",
			})
		},
	}
}
