package provider

import (
	"context"

	"github.com/SPShota/terraform-provider-tensorflow/internal/python"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	datasourceschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ datasource.DataSource = &programDataSource{}

func NewProgramDataSource() datasource.DataSource {
	return &programDataSource{}
}

type programDataSource struct{}

type programDataSourceModel struct {
	Header     types.String `tfsdk:"header"`
	Imports    types.List   `tfsdk:"imports"`
	Statements types.List   `tfsdk:"statements"`
	Content    types.String `tfsdk:"content"`
}

func (d *programDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_program"
}

func (d *programDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = datasourceschema.Schema{
		MarkdownDescription: "Generates a TensorFlow Python program from Python statement strings.",
		Attributes: map[string]datasourceschema.Attribute{
			"header": datasourceschema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Optional file header. Defaults to `# Code generated by TF.tf. DO NOT EDIT.`. Set to an empty string to omit the header.",
			},
			"imports": datasourceschema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				MarkdownDescription: "Optional Python import specs. Values such as `tensorflow as tf` are rendered as `import tensorflow as tf`. Full `import ...` and `from ...` lines are also accepted. Defaults to `tensorflow as tf`.",
			},
			"statements": datasourceschema.ListAttribute{
				ElementType:         types.StringType,
				Required:            true,
				MarkdownDescription: "Python statements to append to the generated program.",
			},
			"content": datasourceschema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Generated Python program content.",
			},
		},
	}
}

func (d *programDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data programDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var imports []string
	if !data.Imports.IsNull() && !data.Imports.IsUnknown() {
		resp.Diagnostics.Append(data.Imports.ElementsAs(ctx, &imports, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
	}

	var rawStatements []string
	resp.Diagnostics.Append(data.Statements.ElementsAs(ctx, &rawStatements, false)...)
	if resp.Diagnostics.HasError() {
		return
	}

	statements := make([]python.Statement, 0, len(rawStatements))
	for _, rawStatement := range rawStatements {
		statement, err := python.RawStatement(rawStatement)
		if err != nil {
			resp.Diagnostics.AddError("Invalid statement", err.Error())
			return
		}
		statements = append(statements, statement)
	}

	program := python.Program{
		Imports:    imports,
		Statements: statements,
	}
	if !data.Header.IsNull() && !data.Header.IsUnknown() {
		program.Header = data.Header.ValueString()
	}

	content, err := program.Render()
	if err != nil {
		resp.Diagnostics.AddError("Unable to render Python program", err.Error())
		return
	}

	data.Content = types.StringValue(content)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
