package python

import (
	"fmt"
	"strings"
)

const DefaultHeader = "# Code generated by TF.tf. DO NOT EDIT."

var DefaultImports = []string{"tensorflow as tf"}

type Program struct {
	Header     string
	Imports    []string
	Statements []Statement
}

func (p Program) Render() (string, error) {
	header := p.Header
	if header == "" {
		header = DefaultHeader
	}

	imports := p.Imports
	if imports == nil {
		imports = DefaultImports
	}

	sections := make([]string, 0, 3)
	if strings.TrimSpace(header) != "" {
		sections = append(sections, strings.TrimRight(header, "\n"))
	}

	importLines, err := renderImports(imports)
	if err != nil {
		return "", err
	}
	if importLines != "" {
		sections = append(sections, importLines)
	}

	statementLines, err := renderStatements(p.Statements)
	if err != nil {
		return "", err
	}
	if statementLines != "" {
		sections = append(sections, statementLines)
	}

	return strings.Join(sections, "\n\n") + "\n", nil
}

func renderImports(imports []string) (string, error) {
	lines := make([]string, 0, len(imports))
	for _, spec := range imports {
		spec = strings.TrimSpace(spec)
		if spec == "" {
			return "", fmt.Errorf("import spec must not be empty")
		}

		if strings.HasPrefix(spec, "import ") || strings.HasPrefix(spec, "from ") {
			lines = append(lines, spec)
			continue
		}

		lines = append(lines, "import "+spec)
	}

	return strings.Join(lines, "\n"), nil
}

func renderStatements(statements []Statement) (string, error) {
	lines := make([]string, 0, len(statements))
	for _, statement := range statements {
		if statement.code == "" {
			return "", fmt.Errorf("statement must not be empty")
		}
		lines = append(lines, statement.code)
	}

	return strings.Join(lines, "\n"), nil
}
