package python

import "testing"

func TestProgramRender(t *testing.T) {
	t.Parallel()

	statement, err := RawStatement("x = tf.constant([1, 2, 3])")
	if err != nil {
		t.Fatalf("RawStatement() returned error: %v", err)
	}

	content, err := Program{Statements: []Statement{statement}}.Render()
	if err != nil {
		t.Fatalf("Render() returned error: %v", err)
	}

	want := "# Code generated by TF.tf. DO NOT EDIT.\n\nimport tensorflow as tf\n\nx = tf.constant([1, 2, 3])\n"
	if content != want {
		t.Fatalf("Render() = %q, want %q", content, want)
	}
}

func TestProgramRenderWithCustomHeaderAndImports(t *testing.T) {
	t.Parallel()

	statement, err := RawStatement("print(tf.__version__)")
	if err != nil {
		t.Fatalf("RawStatement() returned error: %v", err)
	}

	content, err := Program{
		Header:     "# custom",
		Imports:    []string{"tensorflow as tf", "from pathlib import Path"},
		Statements: []Statement{statement},
	}.Render()
	if err != nil {
		t.Fatalf("Render() returned error: %v", err)
	}

	want := "# custom\n\nimport tensorflow as tf\nfrom pathlib import Path\n\nprint(tf.__version__)\n"
	if content != want {
		t.Fatalf("Render() = %q, want %q", content, want)
	}
}

func TestProgramRenderRejectsEmptyImport(t *testing.T) {
	t.Parallel()

	if _, err := (Program{Imports: []string{""}}).Render(); err == nil {
		t.Fatalf("Render() returned nil error")
	}
}

func TestRawStatementRejectsEmptyStatement(t *testing.T) {
	t.Parallel()

	if _, err := RawStatement(""); err == nil {
		t.Fatalf("RawStatement() returned nil error")
	}
}
